//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.travelshop {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Microsoft.ServiceModel.Samples", ConfigurationName="travelshop.ITravelShop")]
    public interface ITravelShop {
        
        // CODEGEN: Parameter 'getCountriesResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/ITravelShop/getCountries", ReplyAction="http://Microsoft.ServiceModel.Samples/ITravelShop/getCountriesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        API.travelshop.getCountriesResponse getCountries(API.travelshop.getCountriesRequest request);
        
        // CODEGEN: Parameter 'getDestinationsResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/ITravelShop/getDestinations", ReplyAction="http://Microsoft.ServiceModel.Samples/ITravelShop/getDestinationsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        API.travelshop.getDestinationsResponse getDestinations(API.travelshop.getDestinationsRequest request);
        
        // CODEGEN: Parameter 'getHotelsResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/ITravelShop/getHotels", ReplyAction="http://Microsoft.ServiceModel.Samples/ITravelShop/getHotelsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        API.travelshop.getHotelsResponse getHotels(API.travelshop.getHotelsRequest request);
        
        // CODEGEN: Parameter 'getRoomTypesResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/ITravelShop/getRoomTypes", ReplyAction="http://Microsoft.ServiceModel.Samples/ITravelShop/getRoomTypesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        API.travelshop.getRoomTypesResponse getRoomTypes(API.travelshop.getRoomTypesRequest request);
        
        // CODEGEN: Parameter 'getMealTypesResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/ITravelShop/getMealTypes", ReplyAction="http://Microsoft.ServiceModel.Samples/ITravelShop/getMealTypesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        API.travelshop.getMealTypesResponse getMealTypes(API.travelshop.getMealTypesRequest request);
        
        // CODEGEN: Parameter 'getOperatorsResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/ITravelShop/getOperators", ReplyAction="http://Microsoft.ServiceModel.Samples/ITravelShop/getOperatorsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        API.travelshop.getOperatorsResponse getOperators(API.travelshop.getOperatorsRequest request);
        
        // CODEGEN: Parameter 'getSearchResponseResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/ITravelShop/getSearchResponse", ReplyAction="http://Microsoft.ServiceModel.Samples/ITravelShop/getSearchResponseResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        API.travelshop.getSearchResponseResponse getSearchResponse(API.travelshop.getSearchResponseRequest request);
        
        // CODEGEN: Parameter 'startProcessesResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/ITravelShop/startProcesses", ReplyAction="http://Microsoft.ServiceModel.Samples/ITravelShop/startProcessesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        API.travelshop.startProcessesResponse startProcesses(API.travelshop.startProcessesRequest request);
        
        // CODEGEN: Parameter 'getPluginsResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/ITravelShop/getPlugins", ReplyAction="http://Microsoft.ServiceModel.Samples/ITravelShop/getPluginsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        API.travelshop.getPluginsResponse getPlugins(API.travelshop.getPluginsRequest request);
        
        // CODEGEN: Parameter 'prms' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/ITravelShop/getStream_4", ReplyAction="http://Microsoft.ServiceModel.Samples/ITravelShop/getStream_4Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        API.travelshop.getStream_4Response getStream_4(API.travelshop.getStream_4Request request);
        
        // CODEGEN: Parameter 'prms' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/ITravelShop/getStream_7", ReplyAction="http://Microsoft.ServiceModel.Samples/ITravelShop/getStream_7Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        API.travelshop.getStream_7Response getStream_7(API.travelshop.getStream_7Request request);
        
        // CODEGEN: Parameter 'getStateResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/ITravelShop/getState", ReplyAction="http://Microsoft.ServiceModel.Samples/ITravelShop/getStateResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        API.travelshop.getStateResponse getState(API.travelshop.getStateRequest request);
        
        // CODEGEN: Parameter 'getResultResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/ITravelShop/getResult", ReplyAction="http://Microsoft.ServiceModel.Samples/ITravelShop/getResultResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        API.travelshop.getResultResponse getResult(API.travelshop.getResultRequest request);
        
        // CODEGEN: Parameter 'queryString' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/ITravelShop/runQuery", ReplyAction="http://Microsoft.ServiceModel.Samples/ITravelShop/runQueryResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        API.travelshop.runQueryResponse runQuery(API.travelshop.runQueryRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCountries", WrapperNamespace="http://Microsoft.ServiceModel.Samples", IsWrapped=true)]
    public partial class getCountriesRequest {
        
        public getCountriesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCountriesResponse", WrapperNamespace="http://Microsoft.ServiceModel.Samples", IsWrapped=true)]
    public partial class getCountriesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Microsoft.ServiceModel.Samples", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataTable getCountriesResult;
        
        public getCountriesResponse() {
        }
        
        public getCountriesResponse(System.Data.DataTable getCountriesResult) {
            this.getCountriesResult = getCountriesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDestinations", WrapperNamespace="http://Microsoft.ServiceModel.Samples", IsWrapped=true)]
    public partial class getDestinationsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Microsoft.ServiceModel.Samples", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string countryCode;
        
        public getDestinationsRequest() {
        }
        
        public getDestinationsRequest(string countryCode) {
            this.countryCode = countryCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDestinationsResponse", WrapperNamespace="http://Microsoft.ServiceModel.Samples", IsWrapped=true)]
    public partial class getDestinationsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Microsoft.ServiceModel.Samples", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataTable getDestinationsResult;
        
        public getDestinationsResponse() {
        }
        
        public getDestinationsResponse(System.Data.DataTable getDestinationsResult) {
            this.getDestinationsResult = getDestinationsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getHotels", WrapperNamespace="http://Microsoft.ServiceModel.Samples", IsWrapped=true)]
    public partial class getHotelsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Microsoft.ServiceModel.Samples", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string countryCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Microsoft.ServiceModel.Samples", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string destString;
        
        public getHotelsRequest() {
        }
        
        public getHotelsRequest(string countryCode, string destString) {
            this.countryCode = countryCode;
            this.destString = destString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getHotelsResponse", WrapperNamespace="http://Microsoft.ServiceModel.Samples", IsWrapped=true)]
    public partial class getHotelsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Microsoft.ServiceModel.Samples", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataTable getHotelsResult;
        
        public getHotelsResponse() {
        }
        
        public getHotelsResponse(System.Data.DataTable getHotelsResult) {
            this.getHotelsResult = getHotelsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getRoomTypes", WrapperNamespace="http://Microsoft.ServiceModel.Samples", IsWrapped=true)]
    public partial class getRoomTypesRequest {
        
        public getRoomTypesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getRoomTypesResponse", WrapperNamespace="http://Microsoft.ServiceModel.Samples", IsWrapped=true)]
    public partial class getRoomTypesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Microsoft.ServiceModel.Samples", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataTable getRoomTypesResult;
        
        public getRoomTypesResponse() {
        }
        
        public getRoomTypesResponse(System.Data.DataTable getRoomTypesResult) {
            this.getRoomTypesResult = getRoomTypesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getMealTypes", WrapperNamespace="http://Microsoft.ServiceModel.Samples", IsWrapped=true)]
    public partial class getMealTypesRequest {
        
        public getMealTypesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getMealTypesResponse", WrapperNamespace="http://Microsoft.ServiceModel.Samples", IsWrapped=true)]
    public partial class getMealTypesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Microsoft.ServiceModel.Samples", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataTable getMealTypesResult;
        
        public getMealTypesResponse() {
        }
        
        public getMealTypesResponse(System.Data.DataTable getMealTypesResult) {
            this.getMealTypesResult = getMealTypesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getOperators", WrapperNamespace="http://Microsoft.ServiceModel.Samples", IsWrapped=true)]
    public partial class getOperatorsRequest {
        
        public getOperatorsRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getOperatorsResponse", WrapperNamespace="http://Microsoft.ServiceModel.Samples", IsWrapped=true)]
    public partial class getOperatorsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Microsoft.ServiceModel.Samples", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataTable getOperatorsResult;
        
        public getOperatorsResponse() {
        }
        
        public getOperatorsResponse(System.Data.DataTable getOperatorsResult) {
            this.getOperatorsResult = getOperatorsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSearchResponse", WrapperNamespace="http://Microsoft.ServiceModel.Samples", IsWrapped=true)]
    public partial class getSearchResponseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Microsoft.ServiceModel.Samples", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string prms;
        
        public getSearchResponseRequest() {
        }
        
        public getSearchResponseRequest(string prms) {
            this.prms = prms;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSearchResponseResponse", WrapperNamespace="http://Microsoft.ServiceModel.Samples", IsWrapped=true)]
    public partial class getSearchResponseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Microsoft.ServiceModel.Samples", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataTable getSearchResponseResult;
        
        public getSearchResponseResponse() {
        }
        
        public getSearchResponseResponse(System.Data.DataTable getSearchResponseResult) {
            this.getSearchResponseResult = getSearchResponseResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="implementationModule.checkState", Namespace="http://schemas.datacontract.org/2004/07/travelShopWindowsService")]
    public partial class implementationModulecheckState : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool _completedField;
        
        private System.Data.DataTable _tableField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool _completed {
            get {
                return this._completedField;
            }
            set {
                this._completedField = value;
                this.RaisePropertyChanged("_completed");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Data.DataTable _table {
            get {
                return this._tableField;
            }
            set {
                this._tableField = value;
                this.RaisePropertyChanged("_table");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="startProcesses", WrapperNamespace="http://Microsoft.ServiceModel.Samples", IsWrapped=true)]
    public partial class startProcessesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Microsoft.ServiceModel.Samples", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string prms;
        
        public startProcessesRequest() {
        }
        
        public startProcessesRequest(string prms) {
            this.prms = prms;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="startProcessesResponse", WrapperNamespace="http://Microsoft.ServiceModel.Samples", IsWrapped=true)]
    public partial class startProcessesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Microsoft.ServiceModel.Samples", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public object startProcessesResult;
        
        public startProcessesResponse() {
        }
        
        public startProcessesResponse(object startProcessesResult) {
            this.startProcessesResult = startProcessesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getPlugins", WrapperNamespace="http://Microsoft.ServiceModel.Samples", IsWrapped=true)]
    public partial class getPluginsRequest {
        
        public getPluginsRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getPluginsResponse", WrapperNamespace="http://Microsoft.ServiceModel.Samples", IsWrapped=true)]
    public partial class getPluginsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Microsoft.ServiceModel.Samples", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public object[] getPluginsResult;
        
        public getPluginsResponse() {
        }
        
        public getPluginsResponse(object[] getPluginsResult) {
            this.getPluginsResult = getPluginsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStream_4", WrapperNamespace="http://Microsoft.ServiceModel.Samples", IsWrapped=true)]
    public partial class getStream_4Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Microsoft.ServiceModel.Samples", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string prms;
        
        public getStream_4Request() {
        }
        
        public getStream_4Request(string prms) {
            this.prms = prms;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStream_4Response", WrapperNamespace="http://Microsoft.ServiceModel.Samples", IsWrapped=true)]
    public partial class getStream_4Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Microsoft.ServiceModel.Samples", Order=0)]
        public System.IO.Stream getStream_4Result;
        
        public getStream_4Response() {
        }
        
        public getStream_4Response(System.IO.Stream getStream_4Result) {
            this.getStream_4Result = getStream_4Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStream_7", WrapperNamespace="http://Microsoft.ServiceModel.Samples", IsWrapped=true)]
    public partial class getStream_7Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Microsoft.ServiceModel.Samples", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string prms;
        
        public getStream_7Request() {
        }
        
        public getStream_7Request(string prms) {
            this.prms = prms;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStream_7Response", WrapperNamespace="http://Microsoft.ServiceModel.Samples", IsWrapped=true)]
    public partial class getStream_7Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Microsoft.ServiceModel.Samples", Order=0)]
        public System.IO.Stream getStream_7Result;
        
        public getStream_7Response() {
        }
        
        public getStream_7Response(System.IO.Stream getStream_7Result) {
            this.getStream_7Result = getStream_7Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getState", WrapperNamespace="http://Microsoft.ServiceModel.Samples", IsWrapped=true)]
    public partial class getStateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Microsoft.ServiceModel.Samples", Order=0)]
        public int prms;
        
        public getStateRequest() {
        }
        
        public getStateRequest(int prms) {
            this.prms = prms;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStateResponse", WrapperNamespace="http://Microsoft.ServiceModel.Samples", IsWrapped=true)]
    public partial class getStateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Microsoft.ServiceModel.Samples", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public API.travelshop.implementationModulecheckState getStateResult;
        
        public getStateResponse() {
        }
        
        public getStateResponse(API.travelshop.implementationModulecheckState getStateResult) {
            this.getStateResult = getStateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getResult", WrapperNamespace="http://Microsoft.ServiceModel.Samples", IsWrapped=true)]
    public partial class getResultRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Microsoft.ServiceModel.Samples", Order=0)]
        public int prms;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Microsoft.ServiceModel.Samples", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string procName;
        
        public getResultRequest() {
        }
        
        public getResultRequest(int prms, string procName) {
            this.prms = prms;
            this.procName = procName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getResultResponse", WrapperNamespace="http://Microsoft.ServiceModel.Samples", IsWrapped=true)]
    public partial class getResultResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Microsoft.ServiceModel.Samples", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataTable getResultResult;
        
        public getResultResponse() {
        }
        
        public getResultResponse(System.Data.DataTable getResultResult) {
            this.getResultResult = getResultResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="runQuery", WrapperNamespace="http://Microsoft.ServiceModel.Samples", IsWrapped=true)]
    public partial class runQueryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Microsoft.ServiceModel.Samples", Order=0)]
        public int timeoutSec;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Microsoft.ServiceModel.Samples", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string queryString;
        
        public runQueryRequest() {
        }
        
        public runQueryRequest(int timeoutSec, string queryString) {
            this.timeoutSec = timeoutSec;
            this.queryString = queryString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="runQueryResponse", WrapperNamespace="http://Microsoft.ServiceModel.Samples", IsWrapped=true)]
    public partial class runQueryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Microsoft.ServiceModel.Samples", Order=0)]
        public int runQueryResult;
        
        public runQueryResponse() {
        }
        
        public runQueryResponse(int runQueryResult) {
            this.runQueryResult = runQueryResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITravelShopChannel : API.travelshop.ITravelShop, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TravelShopClient : System.ServiceModel.ClientBase<API.travelshop.ITravelShop>, API.travelshop.ITravelShop {
        
        public TravelShopClient() {
        }
        
        public TravelShopClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TravelShopClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TravelShopClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TravelShopClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        API.travelshop.getCountriesResponse API.travelshop.ITravelShop.getCountries(API.travelshop.getCountriesRequest request) {
            return base.Channel.getCountries(request);
        }
        
        public System.Data.DataTable getCountries() {
            API.travelshop.getCountriesRequest inValue = new API.travelshop.getCountriesRequest();
            API.travelshop.getCountriesResponse retVal = ((API.travelshop.ITravelShop)(this)).getCountries(inValue);
            return retVal.getCountriesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        API.travelshop.getDestinationsResponse API.travelshop.ITravelShop.getDestinations(API.travelshop.getDestinationsRequest request) {
            return base.Channel.getDestinations(request);
        }
        
        public System.Data.DataTable getDestinations(string countryCode) {
            API.travelshop.getDestinationsRequest inValue = new API.travelshop.getDestinationsRequest();
            inValue.countryCode = countryCode;
            API.travelshop.getDestinationsResponse retVal = ((API.travelshop.ITravelShop)(this)).getDestinations(inValue);
            return retVal.getDestinationsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        API.travelshop.getHotelsResponse API.travelshop.ITravelShop.getHotels(API.travelshop.getHotelsRequest request) {
            return base.Channel.getHotels(request);
        }
        
        public System.Data.DataTable getHotels(string countryCode, string destString) {
            API.travelshop.getHotelsRequest inValue = new API.travelshop.getHotelsRequest();
            inValue.countryCode = countryCode;
            inValue.destString = destString;
            API.travelshop.getHotelsResponse retVal = ((API.travelshop.ITravelShop)(this)).getHotels(inValue);
            return retVal.getHotelsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        API.travelshop.getRoomTypesResponse API.travelshop.ITravelShop.getRoomTypes(API.travelshop.getRoomTypesRequest request) {
            return base.Channel.getRoomTypes(request);
        }
        
        public System.Data.DataTable getRoomTypes() {
            API.travelshop.getRoomTypesRequest inValue = new API.travelshop.getRoomTypesRequest();
            API.travelshop.getRoomTypesResponse retVal = ((API.travelshop.ITravelShop)(this)).getRoomTypes(inValue);
            return retVal.getRoomTypesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        API.travelshop.getMealTypesResponse API.travelshop.ITravelShop.getMealTypes(API.travelshop.getMealTypesRequest request) {
            return base.Channel.getMealTypes(request);
        }
        
        public System.Data.DataTable getMealTypes() {
            API.travelshop.getMealTypesRequest inValue = new API.travelshop.getMealTypesRequest();
            API.travelshop.getMealTypesResponse retVal = ((API.travelshop.ITravelShop)(this)).getMealTypes(inValue);
            return retVal.getMealTypesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        API.travelshop.getOperatorsResponse API.travelshop.ITravelShop.getOperators(API.travelshop.getOperatorsRequest request) {
            return base.Channel.getOperators(request);
        }
        
        public System.Data.DataTable getOperators() {
            API.travelshop.getOperatorsRequest inValue = new API.travelshop.getOperatorsRequest();
            API.travelshop.getOperatorsResponse retVal = ((API.travelshop.ITravelShop)(this)).getOperators(inValue);
            return retVal.getOperatorsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        API.travelshop.getSearchResponseResponse API.travelshop.ITravelShop.getSearchResponse(API.travelshop.getSearchResponseRequest request) {
            return base.Channel.getSearchResponse(request);
        }
        
        public System.Data.DataTable getSearchResponse(string prms) {
            API.travelshop.getSearchResponseRequest inValue = new API.travelshop.getSearchResponseRequest();
            inValue.prms = prms;
            API.travelshop.getSearchResponseResponse retVal = ((API.travelshop.ITravelShop)(this)).getSearchResponse(inValue);
            return retVal.getSearchResponseResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        API.travelshop.startProcessesResponse API.travelshop.ITravelShop.startProcesses(API.travelshop.startProcessesRequest request) {
            return base.Channel.startProcesses(request);
        }
        
        public object startProcesses(string prms) {
            API.travelshop.startProcessesRequest inValue = new API.travelshop.startProcessesRequest();
            inValue.prms = prms;
            API.travelshop.startProcessesResponse retVal = ((API.travelshop.ITravelShop)(this)).startProcesses(inValue);
            return retVal.startProcessesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        API.travelshop.getPluginsResponse API.travelshop.ITravelShop.getPlugins(API.travelshop.getPluginsRequest request) {
            return base.Channel.getPlugins(request);
        }
        
        public object[] getPlugins() {
            API.travelshop.getPluginsRequest inValue = new API.travelshop.getPluginsRequest();
            API.travelshop.getPluginsResponse retVal = ((API.travelshop.ITravelShop)(this)).getPlugins(inValue);
            return retVal.getPluginsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        API.travelshop.getStream_4Response API.travelshop.ITravelShop.getStream_4(API.travelshop.getStream_4Request request) {
            return base.Channel.getStream_4(request);
        }
        
        public System.IO.Stream getStream_4(string prms) {
            API.travelshop.getStream_4Request inValue = new API.travelshop.getStream_4Request();
            inValue.prms = prms;
            API.travelshop.getStream_4Response retVal = ((API.travelshop.ITravelShop)(this)).getStream_4(inValue);
            return retVal.getStream_4Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        API.travelshop.getStream_7Response API.travelshop.ITravelShop.getStream_7(API.travelshop.getStream_7Request request) {
            return base.Channel.getStream_7(request);
        }
        
        public System.IO.Stream getStream_7(string prms) {
            API.travelshop.getStream_7Request inValue = new API.travelshop.getStream_7Request();
            inValue.prms = prms;
            API.travelshop.getStream_7Response retVal = ((API.travelshop.ITravelShop)(this)).getStream_7(inValue);
            return retVal.getStream_7Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        API.travelshop.getStateResponse API.travelshop.ITravelShop.getState(API.travelshop.getStateRequest request) {
            return base.Channel.getState(request);
        }
        
        public API.travelshop.implementationModulecheckState getState(int prms) {
            API.travelshop.getStateRequest inValue = new API.travelshop.getStateRequest();
            inValue.prms = prms;
            API.travelshop.getStateResponse retVal = ((API.travelshop.ITravelShop)(this)).getState(inValue);
            return retVal.getStateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        API.travelshop.getResultResponse API.travelshop.ITravelShop.getResult(API.travelshop.getResultRequest request) {
            return base.Channel.getResult(request);
        }
        
        public System.Data.DataTable getResult(int prms, string procName) {
            API.travelshop.getResultRequest inValue = new API.travelshop.getResultRequest();
            inValue.prms = prms;
            inValue.procName = procName;
            API.travelshop.getResultResponse retVal = ((API.travelshop.ITravelShop)(this)).getResult(inValue);
            return retVal.getResultResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        API.travelshop.runQueryResponse API.travelshop.ITravelShop.runQuery(API.travelshop.runQueryRequest request) {
            return base.Channel.runQuery(request);
        }
        
        public int runQuery(int timeoutSec, string queryString) {
            API.travelshop.runQueryRequest inValue = new API.travelshop.runQueryRequest();
            inValue.timeoutSec = timeoutSec;
            inValue.queryString = queryString;
            API.travelshop.runQueryResponse retVal = ((API.travelshop.ITravelShop)(this)).runQuery(inValue);
            return retVal.runQueryResult;
        }
    }
}
